### ISSUE TITLE
Don't do it this way

### ISSUE THREAD

**Issue by GreenBayRules** [WorldLanguages/ScratchNotifier.cf#14]
![image](https://user-images.githubusercontent.com/11379161/53138918-c6bb8a00-353c-11e9-8a33-2c7ced600b23.png)

Don't do it this way, make it so that the javascript adds that content based on the add alts button rather than having 3 of them set to display:none

**Comment by locness3** [comment]
This would create flexibility, and so we could have unlimited alts this way.

**Comment by locness3** [comment]
#7

**Comment by WorldLanguages** [comment]
Closing in favor of #7
