### ISSUE TITLE
Using flexbox instead of tables for layout

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier.cf#17]
You should use flexbox, tables *were* a great way to make layouts, in the 90s... We are in 2019.

**Comment by WorldLanguages** [comment]
Well, I'm already using tables, and they work, so I don't really see the need to use flexbox.
And fyi, flex didn't exist before 2012 :P

**Comment by locness3** [comment]
Yes, but before 2012, there were already other methods than tables for layouts.
