### ISSUE TITLE
Using sessionStorage instead of a delay for session notifications disabling

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier.cf#18]
If I'm not wrong, the present system uses a delay to know if a session has ended when notifications for this session is disabled. What would be more logical would be to use sessionStorage I guess. Correct me if I'm wrong.

**Comment by WorldLanguages** [comment]
If I recall correctly, I simply used a global variable. Of course, the variable is reset when the session is restarted. I also use a timeout because I don't think more than a day can be considered a single session. People sleep.

**Comment by WorldLanguages** [comment]
@locness3 I did use sessionStorage in the previous version, so you're not wrong about using it :)

**Comment by locness3** [comment]
Ok
