### ISSUE TITLE
Issue with mobile

### ISSUE THREAD

**Issue by FrenchBread49** [WorldLanguages/ScratchNotifier.cf#19]
![Screenshot_20190607-160303](https://user-images.githubusercontent.com/39689073/59137707-ea64dd80-893d-11e9-99a5-1b92b9f05721.png)
What do I do

**Comment by WorldLanguages** [comment]
Thanks for reporting this I'll take a look.

**Comment by WorldLanguages** [comment]
@FrenchBread49 By the way just wondering, did it work before? As in, did you get any background notifications in the past weeks?

**Comment by FrenchBread49** [comment]
I am getting notifications but when I hit the settings it sends me here

**Comment by WorldLanguages** [comment]
Thanks for reporting, this was fixed :)
