### ISSUE TITLE
Got a weird count bug

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier.cf#20]
I always leave a Scratch Notifier tab open and pinned. Idk why, maybe because of cached numbers adding up or something, I got a notification saying "83 unread messages", and the Scratch Notifier showed up 83 on it. When going on Scratch though I had zero messages.

**Comment by locness3** [comment]
Ok, now it says I have 13 messages, but I still have none. wtf is that

**Comment by locness3** [comment]
After, It falled down at zero again, then at 13, then at 77

**Comment by locness3** [comment]
Then back at 0. ❓

**Comment by locness3** [comment]
It looks like it's from the API.
![Capture d’écran 2019-07-03 à 18 19 23](https://user-images.githubusercontent.com/37651007/60608192-29604480-9dbf-11e9-8324-5f072f9147fe.png)

**Comment by WorldLanguages** [comment]
Thanks for reporting this issue, we'll look at the issue. Hopefully it's in our end and not Scratch's.

**Comment by locness3** [comment]
> Hopefully it's in our end and not Scratch's.

It's on Scratch's, it doesn't stop marking random old messages as unread and therefore causes this.

**Comment by locness3** [comment]
Seems fixed.
