### ISSUE TITLE
Using :not(:last-child) for alt accounts borders

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier.cf#21]
Currently, the alt accounts' rows are styled using an html attribute to know if they are not the last alt. You could do `:not(:last-child)` in CSS. This would be practical for #7 .

**Comment by WorldLanguages** [comment]
I was going to use `:not(:last-child)` but I didn't find a way to do "last child visible". Unused alt spots are just hidden, they aren't removed. @locness3, do you know if it's possible to do `:last-child` where display isn't "none"?

**Comment by WorldLanguages** [comment]
Anyway if #7 is worked on, `:last-child` would work just fine, because alt spots would be created/removed dynamically :)

**Comment by locness3** [comment]
I meant using it to show the border or not.

**Comment by WorldLanguages** [comment]
I know! But if you don't use the three alt spots, `last-child` would apply to the third, hidden alt, instead of the last visible alt, and the border would be shown anyway.

**Comment by locness3** [comment]
Ah yes.
