### ISSUE TITLE
Not getting notifications anymore after not using computer for a few days

### ISSUE THREAD

**Issue by hf3i05** [WorldLanguages/ScratchNotifier.cf#29]
Hello, @WorldLanguages,
For some reason, after I didn't use my computer for a few days, I no longer get notifications for new messages from [the ScratchNotifier website](https://scratchnotifier.cf). I do not know why, but today I received 12 messages in the morning, but I didn't receive a notification for even one of them.
Can you help? Am I doing something wrong?

>My device details:
>- OS: Ubuntu 20.04 'Focal Fossa'
>- Browser: [Opera](https://www.opera.com)

**Comment by WorldLanguages** [comment]
Has the tab been discarded? Try clicking on the tab. If it refreshes, then your browser silently killed the tab in the background. If it doesn't refresh, then check the console for errors?

**Comment by hf3i05** [comment]
Nope. It wasn't suspended. I'll check the console for errors tomorrow.

**Comment by hf3i05** [comment]
I'm going to bed now, so I won't be able to answer messages until tomorrow.

**Comment by hf3i05** [comment]
I'm using Ubuntu 20.04 now (still using Opera), and it works.
