### ISSUE TITLE
Mobile version 'no longer available'

### ISSUE THREAD

**Issue by hf3i05** [WorldLanguages/ScratchNotifier.cf#31]
When I go to the [mobile version of Scratch Notifier](m.scratchnotifier.cf), it says 'Sorry, the mobile version is no longer available'. Why is this?

**Comment by lovecodeabc** [comment]
**Sorry, the mobile version is no longer available. Try going to ScratchNotifier.cf on a desktop computer (Windows, Mac, Chromebook, Linux, etc.)** It's discontinued :(

**Comment by ghost** [comment]
> lovecodeabc wrote:
> **Sorry, the mobile version is no longer available. Try going to ScratchNotifier.cf on a desktop computer (Windows, Mac, Chromebook, Linux, etc.)** It's discontinued :(

Oh, ok.
