### ISSUE TITLE
The images aren't loading

### ISSUE THREAD

**Issue by lovecodeabc** [WorldLanguages/ScratchNotifier.cf#33]
![Screenshot 2020-11-17 at 12 35 17 PM](https://user-images.githubusercontent.com/74517386/99425911-7b7d0980-28d1-11eb-9a8c-f94cc209ce8a.png)
See? The images aren't loading.

**Comment by moeenio** [comment]
~~why would you use a chromebook~~

**Comment by lovecodeabc** [comment]
> ~why would you use a chromebook~

i have a chromebook. happy now?
EDIT: i might have to clear the browser cache

**Comment by WorldLanguages** [comment]
This is a Scratch issue.

**Comment by moeenio** [comment]
The heck? What does loading the background have to do wtih Scratch

**Comment by WorldLanguages** [comment]
@locness3, you misunderstood the bug report.

**Comment by moeenio** [comment]
I did!
