### ISSUE TITLE
Everything resets on refresh

### ISSUE THREAD

**Issue by qian-json** [WorldLanguages/ScratchNotifier.cf#36]
When you refresh the page everything resets and you have to start all over again.

**Comment by ghost** [comment]
@Stockriderj Nothing resets. The website keeps its previous state.

**Comment by qian-json** [comment]
@thecoder876 It does for me. It takes me back to the start page.

**Comment by ghost** [comment]
> [ping removed] It does for me. It takes me back to the start page.

@Stockriderj Well, I don't know then.

---
*BTW this is thecoder876, I just changed my username.*

**Comment by qian-json** [comment]
@thecrewmate876 I believe that it redirects to scratchnotifier.cf/about.html when I go to scratchnotifier.cf, but once I enter my username it takes me to scratchnotifier.cf, so when I refresh it takes me to scratchnotifier.cf/about.html, which is where I have to start over again. I'm bad at explaining.

**Comment by ghost** [comment]
> *[ping removed]* I believe that it redirects to scratchnotifier.cf/about.html when I go to scratchnotifier.cf, but once I enter my username it takes me to scratchnotifier.cf, so when I refresh it takes me to scratchnotifier.cf/about.html, which is where I have to start over again. I'm bad at explaining.

@Stockriderj Well, when you visit scratchnotifier.cf for the first time, you get the about.html page content. However, once you get started, it should use the index.html page from the on unless you clear your cookies. Maybe you've made your browser automatically clear cookies every time you restart it? This obivously doesn't apply to the reload thing, but I don't really think you'll be reloading Scratch Notifier a lot.

**Comment by qian-json** [comment]
@thecrewmate876 I use a Clean Master extension. I just turned off the Local Storage choice and it works now. Yay! Thanks
